version: "3"

tasks:
  list:
    vars:
      SOLS:
        sh: find src/ -type f -name 'lc*.rs' | grep -Po '\d+' | sort
    silent: true
    cmds:
      - echo "Solutions:"
      - for: { var: SOLS }
        cmd: echo "- {{ .ITEM }}"
  test-all: cargo test --lib
  time-all: cargo +nightly test --lib -- -Z unstable-options --report-time
  test-*:
    vars:
      ID: "{{ index .MATCH 0 }}"
    cmds:
      - cargo test --lib {{.ID}}
  time-*:
    vars:
      ID: "{{ index .MATCH 0 }}"
    cmds:
      - cargo +nightly test --lib {{.ID}} -- -Z unstable-options --report-time
  watch-*:
    watch: true
    sources:
      - "src/lc{{.ID}}.rs"
    vars:
      ID: "{{ index .MATCH 0 }}"
    cmds:
      - cargo +nightly test --lib {{.ID}} -- -Z unstable-options --report-time
